version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps(actions)

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:15"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps(py)

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: deps(ui)
