version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: UTC
    commit-message:
      prefix: deps(all)

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: pip
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: npm
    directory: /ui
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
