location: East US
name: price-target-job
type: Microsoft.App/jobs
identity:
  type: SystemAssigned
properties:
  configuration:
    triggerType: Schedule
    scheduleTriggerConfig:
      cronExpression: "0 12 * * *"
      parallelism: 1
      replicaCompletionCount: 1
    registries:
    - identity: ''
      passwordSecretRef: assetallocationacrazurecrio-assetallocationacr
      server: assetallocationacr.azurecr.io
      username: assetallocationacr
    replicaRetryLimit: 0
    replicaTimeout: 1800
    secrets:
    - name: assetallocationacrazurecrio-assetallocationacr
    - name: nasdaq-api-key
  environmentId: /subscriptions/eabd0bb1-8f36-4f27-ad86-8b33e02aaeb9/resourceGroups/AssetAllocationRG/providers/Microsoft.App/managedEnvironments/asset-allocation-env
  template:
    containers:
    - env:
      - name: AZURE_STORAGE_ACCOUNT_NAME
        value: assetallocstorage001
      - name: AZURE_CONTAINER_NAME
        value: market-data
      - name: AZURE_CONTAINER_PRICE_TARGETS
        value: price-targets
      - name: NASDAQ_API_KEY
        secretRef: nasdaq-api-key
      - name: AZURE_CONFIG_CONTAINER_NAME
        value: common-data
      - name: HEADLESS_MODE
        value: 'True'
      image: assetallocationacr.azurecr.io/asset-allocation-scraper:latest
      imageType: ContainerImage
      name: price-target-job
      command: ["python", "-m", "scripts.price_target_data.scraper"]
      resources:
        cpu: 1.0
        memory: 2Gi
  workloadProfileName: Consumption
